spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:financasdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    driver-class-name: org.h2.Driver
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}

  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: /h2-console

  sql:
    init:
      mode: never

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN:}
  bot-username: ${TELEGRAM_BOT_USERNAME:CastelarCashBot}

server:
  port: ${PORT:8080}

logging:
  level:
    com.financasbot.bot_financas_whatsapp: ${LOG_LEVEL:DEBUG}
    org.hibernate.SQL: ${HIBERNATE_SQL_LOGGING:DEBUG}